- hosts: localhost
  vars:
    source_key: "{{ lookup('env', 'HOME') }}/ansible/.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    private_playbooks: "git@github.com:victorkamoto/ansible-private.git"
    environ: "server"
  pre_tasks:
  - name: Update APT
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    when: ansible_distribution == "Ubuntu"
    tags:
      - install
      - core
  - name: Update Pacman package cache
    become: true
    pacman:
      update_cache: true
    when: ansible_distribution == "Archlinux"
    tags:
      - install
      - core
  tasks:
  - name: include_tasks
    include_tasks: 
      file: "{{ item }}"
      apply: 
        become_user: vic
    loop:
    - tasks/ssh.yml
    - tasks/git.yml
    - tasks/private-tasks.yml
 
  
        
    


