
- name: Check ansible-private exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/ansible-private"
  register: dir_to_check
  tags:
    - install
    - core

- name: Clone ansible-private repo
  #  use shell instead of git module because of the private key issue
  shell: git clone "{{ private_playbooks }}" "{{ lookup('env', 'HOME') }}/ansible-private"
  when: ansible_facts['os_family'] in ['Debian', 'Archlinux'] and not (dir_to_check.stat.isdir is defined and dir_to_check.stat.isdir)
  # git:
  #   repo: "{{ private_playbooks }}"
  #   dest: "{{ lookup('env', 'HOME') }}/ansible-private"
  #   accept_hostkey: yes
  tags:
    - install
    - core
- name: Include private tasks
  include_tasks: "{{ lookup('env', 'HOME') }}/ansible-private/{{ environ }}.yml"
