- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  when: ansible_facts['os_family'] in ['Debian', 'Archlinux']
  tags:
    - dotfiles
    - install
    - ssh
- name: Install Private SSH Key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  when: ansible_facts['os_family'] in ['Debian', 'Archlinux']
  tags:
    - dotfiles
    - install
    - ssh
- name: Install Public SSH Key
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  when: ansible_facts['os_family'] in ['Debian', 'Archlinux']
  tags:
    - dotfiles
    - install
    - ssh
- name: Set authorized key from id_ed25519.pub
  authorized_key:
    user: "vic"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  when: ansible_facts['os_family'] in ['Debian', 'Archlinux']

      
